#!/usr/bin/env bash
pwd
echo ""

phppkgmgr=""
check_composer_available() {
    echo "Checking composer path"

    if hash composer 2>/dev/null
    then
        phppkgmgr=composer
        return 0
    elif [ -f "vendor/bin/composer" ]
    then
        phppkgmgr=vendor/bin/composer
        return 0
    elif [ -f "./composer.phar" ]
    then
        phppkgmgr=./composer.phar
        return 0
    elif [ -f ".ci/composer.phar" ]
    then
        phppkgmgr=.ci/composer.phar
        return 0
    else
        return 1
    fi
}

download_composer() {
    ./.ci/composer_download
    phppkgmgr=./.ci/composer.phar
}

check_composer_available || download_composer
echo "Composer File Validate:"
$phppkgmgr validate --strict

analyser=""
check_phpstan_available() {
    echo "Checking phpstan path"

    if hash phpstan 2>/dev/null
    then
        analyser=phpstan
        return 0
    elif [ -f "vendor/bin/phpstan" ]
    then
        analyser=vendor/bin/phpstan
        return 0
    elif [ -f ".ci/phpstan.phar" ]
    then
        analyser=.ci/phpstan.phar
        return 0
    else
        return 1
    fi
}

download_phpstan() {
    ./.ci/phpstan_download
    analyser=./.ci/phpstan.phar
}

check_phpstan_available || download_phpstan
echo "use analyser : $analyser"
echo ""
echo "PHP Code Static Analysis:"
git diff --diff-filter=M --name-only --cached|grep -E '\.php$'|xargs -r $analyser analyse --debug --configuration=phpstan.prj.neon --memory-limit=1G