#!/usr/bin/env bash

COMPOSER_FILE=./composer.phar
if hash composer 2>/dev/null
    echo "Composer OK"
else
    echo "Start to downloading Composer ..."
    curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer && echo "Downloading composer success"
fi

if [ -f "vendor/yiisoft/yii2/Yii.php" ]; then
    cp .ci/phpstan.php phpstan.php
    cp .ci/phpstan.neon phpstan.neon
else
    cp .ci/phpstan_without_bootstrap.neon phpstan.neon
fi

if [ -f ".git/config" ]; then
    cp .ci/githook_pre_check .git/hooks/pre-commit
    cp .ci/githook_pre_check .git/hooks/pre-push
    echo "git hook done"
fi

echo "Initialize Done"