#!/usr/bin/env bash
PHPSTAN_FILE=./.ci/phpstan.phar
if [ -f "$PHPSTAN_FILE" ]; then
    echo "PHPStan OK"
else
    echo "Start to downloading PHPStan ..."
    curl --silent -H "User-agent: cURL (https://github.com/php-actions)" -L \
        "https://github.com/phpstan/phpstan/releases/latest/download/phpstan.phar" > $PHPSTAN_FILE
    chmod +x $PHPSTAN_FILE
    echo "PHPStan Download OK"
fi
